// flow-typed signature: 8ee0c31e6859885aa5e544478b8cae2f
// flow-typed version: <<STUB>>/mock-my-api_v^1.1.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-my-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-my-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-my-api/dev/index' {
  declare module.exports: any;
}

declare module 'mock-my-api/lib/index' {
  declare module.exports: any;
}

declare module 'mock-my-api/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-my-api/dev/index.js' {
  declare module.exports: $Exports<'mock-my-api/dev/index'>;
}
declare module 'mock-my-api/lib/index.js' {
  declare module.exports: $Exports<'mock-my-api/lib/index'>;
}
declare module 'mock-my-api/src/index.js' {
  declare module.exports: $Exports<'mock-my-api/src/index'>;
}
