// flow-typed signature: f076c548638f56b71b0d87a86ee3d36b
// flow-typed version: <<STUB>>/react-jss_v^5.3.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-jss/dist/react-jss' {
  declare module.exports: any;
}

declare module 'react-jss/dist/react-jss.min' {
  declare module.exports: any;
}

declare module 'react-jss/karma.conf' {
  declare module.exports: any;
}

declare module 'react-jss/lib/index' {
  declare module.exports: any;
}

declare module 'react-jss/lib/index.test' {
  declare module.exports: any;
}

declare module 'react-jss/lib/SheetsRegistryProvider' {
  declare module.exports: any;
}

declare module 'react-jss/tests.webpack' {
  declare module.exports: any;
}

declare module 'react-jss/tests/index' {
  declare module.exports: any;
}

declare module 'react-jss/tests/index.test' {
  declare module.exports: any;
}

declare module 'react-jss/tests/SheetsRegistryProvider' {
  declare module.exports: any;
}

declare module 'react-jss/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-jss/dist/react-jss.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss'>;
}
declare module 'react-jss/dist/react-jss.min.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss.min'>;
}
declare module 'react-jss/karma.conf.js' {
  declare module.exports: $Exports<'react-jss/karma.conf'>;
}
declare module 'react-jss/lib/index.js' {
  declare module.exports: $Exports<'react-jss/lib/index'>;
}
declare module 'react-jss/lib/index.test.js' {
  declare module.exports: $Exports<'react-jss/lib/index.test'>;
}
declare module 'react-jss/lib/SheetsRegistryProvider.js' {
  declare module.exports: $Exports<'react-jss/lib/SheetsRegistryProvider'>;
}
declare module 'react-jss/tests.webpack.js' {
  declare module.exports: $Exports<'react-jss/tests.webpack'>;
}
declare module 'react-jss/tests/index.js' {
  declare module.exports: $Exports<'react-jss/tests/index'>;
}
declare module 'react-jss/tests/index.test.js' {
  declare module.exports: $Exports<'react-jss/tests/index.test'>;
}
declare module 'react-jss/tests/SheetsRegistryProvider.js' {
  declare module.exports: $Exports<'react-jss/tests/SheetsRegistryProvider'>;
}
declare module 'react-jss/webpack.config.js' {
  declare module.exports: $Exports<'react-jss/webpack.config'>;
}
