// flow-typed signature: 54f55be7a0bb26b1047d0db861fe9465
// flow-typed version: <<STUB>>/react-styleguidist_v^4.6.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-styleguidist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-styleguidist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-styleguidist/bin/styleguidist' {
  declare module.exports: any;
}

declare module 'react-styleguidist/loaders/examples.loader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/loaders/props.loader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/loaders/styleguide.loader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/loaders/utils/chunkify' {
  declare module.exports: any;
}

declare module 'react-styleguidist/loaders/utils/getRequires' {
  declare module.exports: any;
}

declare module 'react-styleguidist/loaders/utils/js' {
  declare module.exports: any;
}

declare module 'react-styleguidist/loaders/utils/removeDoclets' {
  declare module.exports: any;
}

declare module 'react-styleguidist/scripts/build' {
  declare module.exports: any;
}

declare module 'react-styleguidist/scripts/config' {
  declare module.exports: any;
}

declare module 'react-styleguidist/scripts/consts' {
  declare module.exports: any;
}

declare module 'react-styleguidist/scripts/create-server' {
  declare module.exports: any;
}

declare module 'react-styleguidist/scripts/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/scripts/make-webpack-config' {
  declare module.exports: any;
}

declare module 'react-styleguidist/scripts/server' {
  declare module.exports: any;
}

declare module 'react-styleguidist/scripts/utils/error' {
  declare module.exports: any;
}

declare module 'react-styleguidist/scripts/utils/utils' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Code/Code.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Code/CodeRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Code/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Components/Components' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Components/Components.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Components/ComponentsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Components/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ComponentsList/ComponentsList.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ComponentsList/ComponentsListRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ComponentsList/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Editor/Editor' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Editor/Editor.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Editor/EditorLoader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Editor/EditorLoaderRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Editor/EditorRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Editor/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Examples/Examples' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Examples/Examples.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Examples/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Markdown/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Markdown/Markdown' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Markdown/Markdown.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Message/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Message/Message.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Message/MessageRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Methods/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Methods/Methods.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Methods/MethodsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Playground/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Playground/Playground' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Playground/Playground.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Playground/PlaygroundRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/PlaygroundError/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/PlaygroundError/PlaygroundError.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/PlaygroundError/PlaygroundErrorRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Preview/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Preview/Preview' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Preview/Preview.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Props/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Props/Props.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Props/PropsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Props/util' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ReactComponent/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponent' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponent.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponentRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponentRenderer.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Section/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Section/Section' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Section/Section.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Section/SectionRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Sections/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Sections/Sections' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Sections/Sections.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Sections/SectionsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/StyleGuide/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/StyleGuide/StyleGuide' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/StyleGuide/StyleGuide.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/StyleGuide/StyleGuideRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/TableOfContents/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/TableOfContents/TableOfContents' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/TableOfContents/TableOfContents.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/TableOfContents/TableOfContentsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Wrapper/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Wrapper/Wrapper' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Wrapper/Wrapper.spec' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/utils/markdown-to-jsx' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/utils/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-styleguidist/bin/styleguidist.js' {
  declare module.exports: $Exports<'react-styleguidist/bin/styleguidist'>;
}
declare module 'react-styleguidist/loaders/examples.loader.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/examples.loader'>;
}
declare module 'react-styleguidist/loaders/props.loader.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/props.loader'>;
}
declare module 'react-styleguidist/loaders/styleguide.loader.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/styleguide.loader'>;
}
declare module 'react-styleguidist/loaders/utils/chunkify.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/utils/chunkify'>;
}
declare module 'react-styleguidist/loaders/utils/getRequires.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/utils/getRequires'>;
}
declare module 'react-styleguidist/loaders/utils/js.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/utils/js'>;
}
declare module 'react-styleguidist/loaders/utils/removeDoclets.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/utils/removeDoclets'>;
}
declare module 'react-styleguidist/scripts/build.js' {
  declare module.exports: $Exports<'react-styleguidist/scripts/build'>;
}
declare module 'react-styleguidist/scripts/config.js' {
  declare module.exports: $Exports<'react-styleguidist/scripts/config'>;
}
declare module 'react-styleguidist/scripts/consts.js' {
  declare module.exports: $Exports<'react-styleguidist/scripts/consts'>;
}
declare module 'react-styleguidist/scripts/create-server.js' {
  declare module.exports: $Exports<'react-styleguidist/scripts/create-server'>;
}
declare module 'react-styleguidist/scripts/index.js' {
  declare module.exports: $Exports<'react-styleguidist/scripts/index'>;
}
declare module 'react-styleguidist/scripts/make-webpack-config.js' {
  declare module.exports: $Exports<'react-styleguidist/scripts/make-webpack-config'>;
}
declare module 'react-styleguidist/scripts/server.js' {
  declare module.exports: $Exports<'react-styleguidist/scripts/server'>;
}
declare module 'react-styleguidist/scripts/utils/error.js' {
  declare module.exports: $Exports<'react-styleguidist/scripts/utils/error'>;
}
declare module 'react-styleguidist/scripts/utils/utils.js' {
  declare module.exports: $Exports<'react-styleguidist/scripts/utils/utils'>;
}
declare module 'react-styleguidist/src/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Code/Code.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Code/Code.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Code/CodeRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Code/CodeRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Code/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Code/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Components/Components.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Components/Components'>;
}
declare module 'react-styleguidist/src/rsg-components/Components/Components.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Components/Components.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Components/ComponentsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Components/ComponentsRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Components/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Components/index'>;
}
declare module 'react-styleguidist/src/rsg-components/ComponentsList/ComponentsList.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ComponentsList/ComponentsList.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/ComponentsList/ComponentsListRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ComponentsList/ComponentsListRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/ComponentsList/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ComponentsList/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Editor/Editor.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Editor/Editor'>;
}
declare module 'react-styleguidist/src/rsg-components/Editor/Editor.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Editor/Editor.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Editor/EditorLoader.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Editor/EditorLoader'>;
}
declare module 'react-styleguidist/src/rsg-components/Editor/EditorLoaderRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Editor/EditorLoaderRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Editor/EditorRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Editor/EditorRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Editor/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Editor/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Examples/Examples.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Examples/Examples'>;
}
declare module 'react-styleguidist/src/rsg-components/Examples/Examples.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Examples/Examples.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Examples/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Examples/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Markdown/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Markdown/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Markdown/Markdown.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Markdown/Markdown'>;
}
declare module 'react-styleguidist/src/rsg-components/Markdown/Markdown.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Markdown/Markdown.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Message/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Message/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Message/Message.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Message/Message.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Message/MessageRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Message/MessageRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Methods/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Methods/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Methods/Methods.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Methods/Methods.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Methods/MethodsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Methods/MethodsRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Playground/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Playground/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Playground/Playground.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Playground/Playground'>;
}
declare module 'react-styleguidist/src/rsg-components/Playground/Playground.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Playground/Playground.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Playground/PlaygroundRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Playground/PlaygroundRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/PlaygroundError/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/PlaygroundError/index'>;
}
declare module 'react-styleguidist/src/rsg-components/PlaygroundError/PlaygroundError.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/PlaygroundError/PlaygroundError.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/PlaygroundError/PlaygroundErrorRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/PlaygroundError/PlaygroundErrorRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Preview/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Preview/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Preview/Preview.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Preview/Preview'>;
}
declare module 'react-styleguidist/src/rsg-components/Preview/Preview.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Preview/Preview.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Props/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Props/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Props/Props.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Props/Props.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Props/PropsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Props/PropsRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Props/util.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Props/util'>;
}
declare module 'react-styleguidist/src/rsg-components/ReactComponent/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ReactComponent/index'>;
}
declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponent.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ReactComponent/ReactComponent'>;
}
declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponent.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ReactComponent/ReactComponent.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponentRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ReactComponent/ReactComponentRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponentRenderer.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ReactComponent/ReactComponentRenderer.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Section/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Section/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Section/Section.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Section/Section'>;
}
declare module 'react-styleguidist/src/rsg-components/Section/Section.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Section/Section.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Section/SectionRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Section/SectionRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Sections/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Sections/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Sections/Sections.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Sections/Sections'>;
}
declare module 'react-styleguidist/src/rsg-components/Sections/Sections.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Sections/Sections.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/Sections/SectionsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Sections/SectionsRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/StyleGuide/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/StyleGuide/index'>;
}
declare module 'react-styleguidist/src/rsg-components/StyleGuide/StyleGuide.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/StyleGuide/StyleGuide'>;
}
declare module 'react-styleguidist/src/rsg-components/StyleGuide/StyleGuide.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/StyleGuide/StyleGuide.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/StyleGuide/StyleGuideRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/StyleGuide/StyleGuideRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/TableOfContents/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/TableOfContents/index'>;
}
declare module 'react-styleguidist/src/rsg-components/TableOfContents/TableOfContents.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/TableOfContents/TableOfContents'>;
}
declare module 'react-styleguidist/src/rsg-components/TableOfContents/TableOfContents.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/TableOfContents/TableOfContents.spec'>;
}
declare module 'react-styleguidist/src/rsg-components/TableOfContents/TableOfContentsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/TableOfContents/TableOfContentsRenderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Wrapper/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Wrapper/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Wrapper/Wrapper.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Wrapper/Wrapper'>;
}
declare module 'react-styleguidist/src/rsg-components/Wrapper/Wrapper.spec.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Wrapper/Wrapper.spec'>;
}
declare module 'react-styleguidist/src/utils/markdown-to-jsx.js' {
  declare module.exports: $Exports<'react-styleguidist/src/utils/markdown-to-jsx'>;
}
declare module 'react-styleguidist/src/utils/utils.js' {
  declare module.exports: $Exports<'react-styleguidist/src/utils/utils'>;
}
