// flow-typed signature: 616b1ff692ab344bcb2889c3f8298c7d
// flow-typed version: <<STUB>>/react-perf-tool_v^0.1.7/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-perf-tool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-perf-tool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-perf-tool/lib/react-perf-tool' {
  declare module.exports: any;
}

declare module 'react-perf-tool/lib/react-perf-tool.min' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/components/ChartComponent' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/components/ReactPerfTool' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/components/Settings' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/components/Tab' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/components/TabHeader' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/components/TabManager' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/components/TimeWasted' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/constants/defaultSettings' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/constants/excludedComponents' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/constants/excludedSettings' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/constants/features' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/index' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/utils/formatTime' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/utils/getUserSettings' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/utils/setUserSettings' {
  declare module.exports: any;
}

declare module 'react-perf-tool/src/utils/titleize' {
  declare module.exports: any;
}

declare module 'react-perf-tool/test/component/setup' {
  declare module.exports: any;
}

declare module 'react-perf-tool/test/component/test.spec' {
  declare module.exports: any;
}

declare module 'react-perf-tool/test/unit/getUserSettings.spec' {
  declare module.exports: any;
}

declare module 'react-perf-tool/test/unit/setUserSettings.spec' {
  declare module.exports: any;
}

declare module 'react-perf-tool/test/unit/titleize' {
  declare module.exports: any;
}

declare module 'react-perf-tool/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-perf-tool/lib/react-perf-tool.js' {
  declare module.exports: $Exports<'react-perf-tool/lib/react-perf-tool'>;
}
declare module 'react-perf-tool/lib/react-perf-tool.min.js' {
  declare module.exports: $Exports<'react-perf-tool/lib/react-perf-tool.min'>;
}
declare module 'react-perf-tool/src/components/ChartComponent.js' {
  declare module.exports: $Exports<'react-perf-tool/src/components/ChartComponent'>;
}
declare module 'react-perf-tool/src/components/ReactPerfTool.js' {
  declare module.exports: $Exports<'react-perf-tool/src/components/ReactPerfTool'>;
}
declare module 'react-perf-tool/src/components/Settings.js' {
  declare module.exports: $Exports<'react-perf-tool/src/components/Settings'>;
}
declare module 'react-perf-tool/src/components/Tab.js' {
  declare module.exports: $Exports<'react-perf-tool/src/components/Tab'>;
}
declare module 'react-perf-tool/src/components/TabHeader.js' {
  declare module.exports: $Exports<'react-perf-tool/src/components/TabHeader'>;
}
declare module 'react-perf-tool/src/components/TabManager.js' {
  declare module.exports: $Exports<'react-perf-tool/src/components/TabManager'>;
}
declare module 'react-perf-tool/src/components/TimeWasted.js' {
  declare module.exports: $Exports<'react-perf-tool/src/components/TimeWasted'>;
}
declare module 'react-perf-tool/src/constants/defaultSettings.js' {
  declare module.exports: $Exports<'react-perf-tool/src/constants/defaultSettings'>;
}
declare module 'react-perf-tool/src/constants/excludedComponents.js' {
  declare module.exports: $Exports<'react-perf-tool/src/constants/excludedComponents'>;
}
declare module 'react-perf-tool/src/constants/excludedSettings.js' {
  declare module.exports: $Exports<'react-perf-tool/src/constants/excludedSettings'>;
}
declare module 'react-perf-tool/src/constants/features.js' {
  declare module.exports: $Exports<'react-perf-tool/src/constants/features'>;
}
declare module 'react-perf-tool/src/index.js' {
  declare module.exports: $Exports<'react-perf-tool/src/index'>;
}
declare module 'react-perf-tool/src/utils/formatTime.js' {
  declare module.exports: $Exports<'react-perf-tool/src/utils/formatTime'>;
}
declare module 'react-perf-tool/src/utils/getUserSettings.js' {
  declare module.exports: $Exports<'react-perf-tool/src/utils/getUserSettings'>;
}
declare module 'react-perf-tool/src/utils/setUserSettings.js' {
  declare module.exports: $Exports<'react-perf-tool/src/utils/setUserSettings'>;
}
declare module 'react-perf-tool/src/utils/titleize.js' {
  declare module.exports: $Exports<'react-perf-tool/src/utils/titleize'>;
}
declare module 'react-perf-tool/test/component/setup.js' {
  declare module.exports: $Exports<'react-perf-tool/test/component/setup'>;
}
declare module 'react-perf-tool/test/component/test.spec.js' {
  declare module.exports: $Exports<'react-perf-tool/test/component/test.spec'>;
}
declare module 'react-perf-tool/test/unit/getUserSettings.spec.js' {
  declare module.exports: $Exports<'react-perf-tool/test/unit/getUserSettings.spec'>;
}
declare module 'react-perf-tool/test/unit/setUserSettings.spec.js' {
  declare module.exports: $Exports<'react-perf-tool/test/unit/setUserSettings.spec'>;
}
declare module 'react-perf-tool/test/unit/titleize.js' {
  declare module.exports: $Exports<'react-perf-tool/test/unit/titleize'>;
}
declare module 'react-perf-tool/webpack.config.js' {
  declare module.exports: $Exports<'react-perf-tool/webpack.config'>;
}
